#!/usr/bin/env bash
#
# Boot the wolfIP ZCU102 app via JTAG (Platform Cable II / Digilent).
# Sourced from anywhere; assumes a hw_server reachable on localhost
# (the default when Vitis is local).
#
# Required env (no built-in defaults; set per-developer):
#   XSDB         - path to Vitis xsdb binary
#                  (e.g. /opt/Xilinx/2025.2/Vitis/bin/xsdb)
#   PSU_INIT_TCL - path to a ZCU102 psu_init.tcl, generated by Vitis
#                  for a base design that matches your board (DDR,
#                  MIO pinmux, IOPLL clocks). The PetaLinux hw-
#                  description directory contains one.
#   OBJCOPY      - aarch64 objcopy binary, e.g.
#                  aarch64-none-elf-objcopy on PATH
#
# Optional env (sensible defaults):
#   APP_ELF      - default: ${PORT_DIR}/app.elf
#   APP_BIN      - default: ${PORT_DIR}/app.bin (objcopy'd here)
#
# Usage (from the port directory):
#   XSDB=/opt/Xilinx/2025.2/Vitis/bin/xsdb \
#   PSU_INIT_TCL=/path/to/psu_init.tcl \
#   OBJCOPY=aarch64-none-elf-objcopy \
#   ./jtag/boot.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT_DIR="$(dirname "${SCRIPT_DIR}")"

: "${XSDB:?XSDB is required (path to Vitis xsdb binary)}"
: "${PSU_INIT_TCL:?PSU_INIT_TCL is required (path to a ZCU102 psu_init.tcl)}"
: "${OBJCOPY:?OBJCOPY is required (aarch64 objcopy binary on PATH or absolute path)}"
APP_ELF="${APP_ELF:-${PORT_DIR}/app.elf}"
APP_BIN="${APP_BIN:-${PORT_DIR}/app.bin}"

if ! command -v "${XSDB}" >/dev/null 2>&1 && [[ ! -x "${XSDB}" ]]; then
    echo "ERROR: xsdb not found / not executable: ${XSDB}" >&2
    exit 1
fi
if [[ ! -f "${PSU_INIT_TCL}" ]]; then
    echo "ERROR: psu_init.tcl not found at ${PSU_INIT_TCL}" >&2
    exit 1
fi
if ! command -v "${OBJCOPY}" >/dev/null 2>&1 && [[ ! -x "${OBJCOPY}" ]]; then
    echo "ERROR: objcopy not found / not executable: ${OBJCOPY}" >&2
    exit 1
fi
if [[ ! -f "${APP_ELF}" ]]; then
    echo "ERROR: app.elf not found at ${APP_ELF}. Run 'make' first." >&2
    exit 1
fi

# Generate flat binary (PT_LOAD segments concatenated by physical addr).
echo "Generating app.bin from app.elf..."
"${OBJCOPY}" -O binary "${APP_ELF}" "${APP_BIN}"

echo "JTAG boot ZCU102 wolfIP app"
echo "  xsdb         : ${XSDB}"
echo "  psu_init.tcl : ${PSU_INIT_TCL}"
echo "  app.elf      : ${APP_ELF}"
echo "  app.bin      : ${APP_BIN} ($(stat -c%s "${APP_BIN}") bytes)"
echo

export APP_ELF APP_BIN PSU_INIT_TCL APP_LOAD_ADDR

"${XSDB}" "${SCRIPT_DIR}/boot.tcl"

echo
echo "App is running. Watch UART:"
echo "  uart-monitor tail ZYNQMP_ZCU102_UART0"
