#!/bin/sh
# wolfip-radvd.sh - run radvd on a wolfIP test interface
#
# Copyright (C) 2026 wolfSSL Inc.
# This file is part of wolfIP TCP/IP stack, distributed under the GPLv3.
#
# Advertises a documentation prefix on a TAP interface so that wolfIP can
# configure itself by SLAAC from a real router implementation, rather than
# from a Router Advertisement the test wrote itself.
#
#   sudo tools/scripts/wolfip-radvd.sh start [iface] [prefix]
#   sudo tools/scripts/wolfip-radvd.sh stop  [iface]
#   sudo tools/scripts/wolfip-radvd.sh status
#
# Defaults match src/test/test_ipv6_slaac.c: wtcp0 and 2001:db8:1:2::/64.
#
# radvd refuses to advertise on an interface that does not have IPv6
# forwarding enabled - it will not act as a router on a host - so this turns
# it on for the one interface and puts it back on stop.

set -e

ACTION="${1:-start}"
IFACE="${2:-wtcp0}"
PREFIX="${3:-2001:db8:1:2::/64}"
HOSTADDR="${4:-2001:db8:1:2::1/64}"

CONF="/tmp/wolfip-radvd-${IFACE}.conf"
PIDFILE="/tmp/wolfip-radvd-${IFACE}.pid"

die() { echo "wolfip-radvd: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "must run as root"

case "$ACTION" in
start)
    command -v radvd >/dev/null 2>&1 || die "radvd is not installed"
    ip link show "$IFACE" >/dev/null 2>&1 || \
        die "interface $IFACE does not exist (start the wolfIP test first)"

    # radvd will not advertise unless the interface forwards.
    sysctl -qw "net.ipv6.conf.${IFACE}.forwarding=1"
    # An address in the prefix, so the host can reach whatever wolfIP picks.
    ip -6 addr replace "$HOSTADDR" dev "$IFACE" nodad

    cat > "$CONF" <<EOF
# Generated by tools/scripts/wolfip-radvd.sh - do not edit.
interface ${IFACE}
{
    AdvSendAdvert on;
    # Advertise often, and answer Router Solicitations at once, so a test
    # does not sit waiting for the default multi-minute interval.
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 10;
    AdvDefaultLifetime 1800;

    prefix ${PREFIX}
    {
        AdvOnLink on;
        # The flag that tells a host it may form an address from this
        # prefix. Without it SLAAC does nothing.
        AdvAutonomous on;
        AdvRouterAddr off;
        AdvValidLifetime 7200;
        AdvPreferredLifetime 3600;
    };
};
EOF

    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then
        echo "wolfip-radvd: already running on $IFACE"
        exit 0
    fi
    radvd -C "$CONF" -p "$PIDFILE" -m stderr_syslog
    echo "wolfip-radvd: advertising $PREFIX on $IFACE (pid $(cat "$PIDFILE"))"
    ;;

stop)
    if [ -f "$PIDFILE" ]; then
        kill "$(cat "$PIDFILE")" 2>/dev/null || true
        rm -f "$PIDFILE"
    fi
    rm -f "$CONF"
    # Leave the interface as we found it.
    sysctl -qw "net.ipv6.conf.${IFACE}.forwarding=0" 2>/dev/null || true
    echo "wolfip-radvd: stopped on $IFACE"
    ;;

status)
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; then
        echo "running (pid $(cat "$PIDFILE"))"
    else
        echo "not running"
        exit 1
    fi
    ;;

*)
    die "usage: $0 {start|stop|status} [iface] [prefix] [hostaddr]"
    ;;
esac
