#!/bin/bash
#
# gen_certs.sh - generate the EC P-256 test PKI for the wired 802.1X
# EAP-TLS demo. Produces BOTH:
#   - ../dot1x_certs.h : client cert + client key (PKCS#8) + CA, as DER C
#     arrays, embedded into the STM32H563 firmware (the supplicant side).
#   - host/ : ca.pem, server.pem, server.key for the hostapd authenticator.
#
# One CA signs both the client (CN alice@wolfip.local) and the server, so
# the firmware and hostapd trust each other. These are THROWAWAY TEST
# CREDENTIALS - never use them in production. Re-run to rotate; commit the
# regenerated ../dot1x_certs.h and host/* together so they stay consistent.
#
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/host"
HDR="$HERE/../dot1x_certs.h"
DAYS=3650
CLIENT_CN="alice@wolfip.local"
SERVER_CN="wolfip-auth.local"

mkdir -p "$OUT"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "== CA (EC P-256, CN 'wolfIP EAP Test CA') =="
openssl ecparam -name prime256v1 -genkey -noout -out "$OUT/ca.key"
openssl req -x509 -new -key "$OUT/ca.key" -days "$DAYS" \
    -subj "/CN=wolfIP EAP Test CA" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -out "$OUT/ca.pem"

echo "== client (CN '$CLIENT_CN', EKU clientAuth) =="
openssl ecparam -name prime256v1 -genkey -noout -out "$TMP/client.key"
openssl req -new -key "$TMP/client.key" -subj "/CN=$CLIENT_CN" -out "$TMP/client.csr"
openssl x509 -req -in "$TMP/client.csr" -CA "$OUT/ca.pem" -CAkey "$OUT/ca.key" \
    -CAcreateserial -days "$DAYS" -out "$TMP/client.pem" \
    -extfile <(printf "extendedKeyUsage=clientAuth\nkeyUsage=critical,digitalSignature")

echo "== server (CN '$SERVER_CN', EKU serverAuth) =="
openssl ecparam -name prime256v1 -genkey -noout -out "$OUT/server.key"
openssl req -new -key "$OUT/server.key" -subj "/CN=$SERVER_CN" -out "$TMP/server.csr"
openssl x509 -req -in "$TMP/server.csr" -CA "$OUT/ca.pem" -CAkey "$OUT/ca.key" \
    -CAcreateserial -days "$DAYS" -out "$OUT/server.pem" \
    -extfile <(printf "extendedKeyUsage=serverAuth\nkeyUsage=critical,digitalSignature,keyEncipherment")

# DER conversions for the firmware (wolfSSL loads DER directly, no PEM
# decoder needed on the MCU).
openssl x509 -in "$TMP/client.pem" -outform der -out "$TMP/client.der"
openssl pkcs8 -topk8 -nocrypt -in "$TMP/client.key" -outform der -out "$TMP/client.key.der"
openssl x509 -in "$OUT/ca.pem" -outform der -out "$TMP/ca.der"

emit_array() {
    # $1 = der file, $2 = C identifier
    printf 'static const unsigned char %s[] = {\n' "$2"
    od -An -v -tx1 "$1" | tr -s ' ' | sed 's/^ //; s/ /, 0x/g; s/^/    0x/; s/$/,/'
    printf '};\nstatic const unsigned int %s_len = sizeof(%s);\n\n' "$2" "$2"
}

echo "== writing $HDR =="
{
    echo "/* dot1x_certs.h - EC P-256 TEST credentials for the wired 802.1X"
    echo " * EAP-TLS demo. GENERATED by dot1x/gen_certs.sh - do not edit by hand."
    echo " * THROWAWAY TEST CREDENTIALS, NOT FOR PRODUCTION. The matching server"
    echo " * cert/key + CA for hostapd live in dot1x/host/. */"
    echo "#ifndef DOT1X_CERTS_H"
    echo "#define DOT1X_CERTS_H"
    echo ""
    echo "/* EAP identity; must match hostapd's eap_user file. */"
    echo "#define DOT1X_EAP_IDENTITY \"$CLIENT_CN\""
    echo ""
    emit_array "$TMP/client.der"     "dot1x_client_cert"
    emit_array "$TMP/client.key.der" "dot1x_client_key"
    emit_array "$TMP/ca.der"         "dot1x_ca_cert"
    echo "#endif /* DOT1X_CERTS_H */"
} > "$HDR"

echo ""
echo "Done."
echo "  firmware header : $HDR"
echo "  hostapd certs   : $OUT/{ca.pem,server.pem,server.key}"
