// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// cyw43_pio //
// --------- //

#define cyw43_pio_wrap_target 0
#define cyw43_pio_wrap 8
#define cyw43_pio_pio_version 0

static const uint16_t cyw43_pio_program_instructions[] = {
            //     .wrap_target
    0x6020, //  0: out    x, 32           side 0
    0x6040, //  1: out    y, 32           side 0
    0xe081, //  2: set    pindirs, 1      side 0
    0x6001, //  3: out    pins, 1         side 0
    0x1043, //  4: jmp    x--, 3          side 1
    0xe080, //  5: set    pindirs, 0      side 0
    0xa042, //  6: nop                    side 0
    0x5001, //  7: in     pins, 1         side 1
    0x0087, //  8: jmp    y--, 7          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cyw43_pio_program = {
    .instructions = cyw43_pio_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = cyw43_pio_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cyw43_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cyw43_pio_wrap_target, offset + cyw43_pio_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

